name: IP Whitelisting Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        type: string
        options:
          - UAT
          - PROD
          - PostgreSQL
      ip_address:
        description: 'Provide your IPv4 or IPv6 address/range'
        required: true
        type: string
        default: 192.x.x.x